### ISSUE TITLE
No support for Snes9x-rr

### ISSUE THREAD

**Issue by FirenX** [Spiraster/ASLScripts#3]
There is a certain version of Snes9x that supports Lua-scripts and debugging that is not supported by any Autosplitter yet. I couldn't find out about the RAM offsets of that emulator. Thus I'd ask you to do it if you can. The emulator in question can be found in the binary files of the most recent release here:
https://github.com/FirenX/emu-coop/releases

I have no clue where the guys I forked it from got it from. Every Snes9x-rr version I found was only based on 1.52 but this one is 1.54.

The ASLScript of yours that would benefit from that information is the ALttP script.

**Comment by Spiraster** [comment]
I've added support for 1.52-rr r185 (which is the newest as far as I can tell) and for that 1.54 build you have.

**Comment by FirenX** [comment]
Works great. Thanks a lot.

**Comment by codemann8** [comment]
@Spiraster This seems to have stopped working on newer versions of Snes9x-rr: Here is a link to the latest release: https://github.com/gocha/snes9x-rr/releases
