### ISSUE TITLE
Super Mario World splits are triggering twice

### ISSUE THREAD

**Issue by charleshacks** [Spiraster/ASLScripts#9]
Thanks for your great work on this Spiraster.

I'm running into an issue where splits on SMW are being triggered twice for each level completion, and unfortunately I'm not familiar enough with livesplit to debug it myself. The issue is occurring on both Snes9x 1.53 64-bit, and BizHawk with BSNES.

Any thoughts?

**Comment by charleshacks** [comment]
I figured out what was happening here.. I had the autosplitter loaded through both the splits editor, and separately though the layout, which was causing two autosplits to run simultaneously.

**Comment by Spiraster** [comment]
Ah yeah, it's annoying that that can happen. Glad you were able to figure it out! :)

**Comment by philipbower122** [comment]
> I figured out what was happening here.. I had the autosplitter loaded through both the splits editor, and separately though the layout, which was causing two autosplits to run simultaneously.

This happened with me. but this still has some bugs. Check out Boss Parade issue.
